# Generated by Django 3.2.5 on 2024-02-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_comment_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                default=123, on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="projects.issue"
            ),
            preserve_default=False,
        ),
    ]
